language: rust

cache: cargo

after_success: |
  if [ "$TRAVIS_RUST_VERSION" = stable ]; then
    # bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
